alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
databases:
- engine: PG
  name: db
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: backend
    match:
      path:
        prefix: /
name: qubic-metrics
region: nyc
services:
- build_command: pnpm run build:digitalocean
  environment_slug: node-js
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
  - key: GITHUB_ACCESS_TOKEN
    scope: RUN_AND_BUILD_TIME
    value: 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
  github:
    branch: main
    deploy_on_push: true
    repo: tomaspozo/qubic-metrics-backend
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: backend
  run_command: pnpm start
  source_dir: /
